// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/404": {
    params: {};
  };
  "/": {
    params: {};
  };
  "/chat/:session_id": {
    params: {
      "session_id": string;
    };
  };
  "/about": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "routes/[404]._index.jsx": {
    id: "404";
    page: "/404";
  } | {
    id: "routes/[404]._index";
    page: "/*";
  };
  "root.jsx": {
    id: "root";
    page: "/404" | "/" | "/chat/:session_id" | "/about" | "/chat" | "/*";
  };
  "routes/[chat].$[session_id]._index.jsx": {
    id: "routes/[chat].$[session_id]._index";
    page: "/chat/:session_id";
  };
  "routes/[about]._index.jsx": {
    id: "routes/[about]._index";
    page: "/about";
  };
  "routes/[chat]._index.jsx": {
    id: "routes/[chat]._index";
    page: "/chat";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
};